"""Add composite index to MasterVariable for performance

Revision ID: 23fa109ad4f2
Revises: ae760d289a69
Create Date: 2025-12-03 21:18:39.155609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa109ad4f2'
down_revision = 'ae760d289a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.create_index('idx_master_variable_name_date', ['variable_name', 'date_recorded'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_variable_date_recorded'), ['date_recorded'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_variable_date_recorded'))
        batch_op.drop_index('idx_master_variable_name_date')

    # ### end Alembic commands ###
