"""Add master_variable table for centralized rates

Revision ID: 4197b8619e9b
Revises: 4c3e54bfde18
Create Date: 2025-10-23 14:59:50.113912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4197b8619e9b'
down_revision = '4c3e54bfde18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=64), nullable=False),
    sa.Column('variable_value', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('date_recorded', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_variable_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_variable_variable_name'), ['variable_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_variable_variable_name'))
        batch_op.drop_index(batch_op.f('ix_master_variable_category'))

    op.drop_table('master_variable')
    # ### end Alembic commands ###
