"""Add financial_cache JSON column for performance optimization

Revision ID: 9fccfb87603f
Revises: 23fa109ad4f2
Create Date: 2025-12-03 21:35:27.502944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fccfb87603f'
down_revision = '23fa109ad4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_cache', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('financial_cache')

    # ### end Alembic commands ###
