"""Add periodo and duracion to FixedCost

Revision ID: fe8ba629985e
Revises: 8cbddb36c16a
Create Date: 2025-10-30 21:58:00.479731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8ba629985e'
down_revision = '8cbddb36c16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### BEGIN PASTE ###
    
    # Step 1: Add columns as nullable
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_inicio', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('duracion_meses', sa.Integer(), nullable=True, server_default='1'))

    # Step 2: Update existing NULL rows to the default value
    op.execute('UPDATE fixed_cost SET periodo_inicio = 0 WHERE periodo_inicio IS NULL')
    op.execute('UPDATE fixed_cost SET duracion_meses = 1 WHERE duracion_meses IS NULL')

    # Step 3: Alter columns to be NOT NULL
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.alter_column('periodo_inicio',
                       existing_type=sa.Integer(),
                       nullable=False,
                       server_default='0')
        batch_op.alter_column('duracion_meses',
                       existing_type=sa.Integer(),
                       nullable=False,
                       server_default='1')
    # ### END PASTE ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.drop_column('duracion_meses')
        batch_op.drop_column('periodo_inicio')

    # ### end Alembic commands ###
